#MediationZone Export
#Fri Jul 17 13:53:17 UTC 2026
mzexport.mzname=CMD
mzexport.mzdetailedversion=9.3.1.1
mzexport.hostname=ns2cmdapp1
mzexport.mzrepository=tag-mz-9.3.1.1-RC0-15-g25198cc
mzexport.creation=1784296397219
mzexport.mzversion=9.3.1.1
Configuration/BRIMCM_APIs_Collection/APL\ Code_order=Configuration/BRIMCM_APIs_Collection/APL Code/BRIMCM_APIs_Collection.APL_Collection_Misc
Configuration/BRIMCM_APIs_Collection/APL\ Code/BRIMCM_APIs_Collection.APL_Collection_Misc=BRIMCM_APIs_Collection.APL_Collection_Misc
Configuration/BRIMCM_APIs_Collection/APL\ Code/BRIMCM_APIs_Collection.APL_Collection_Misc_dependencies=Configuration/BRIMCM_APIs_Collection/Open API Profile/BRIMCM_APIs_Collection.PRF_OpenAPI_Collection_Misc,Configuration/BRIMCM_APIs_Common/APL Code/BRIMCM_APIs_Common.APL_FUNCTIONS,Configuration/Common/APL Code/Common.APL_CONSTANTS,Configuration/Common/External Reference Profile/Common.DB_External_Reference,System/Access Group/Cust_Admin,System/Access Group/Cust_Support,System/User/CUSTADM
mzexport.username=AD69583
